### PR TITLE
Update Header.js - fixing logo

### PR DESCRIPTION
**Pull request by Sophie-GelinasGagne**

### CODE REVIEW

**Comment by danbjoseph** [comment]
this change looks straight forward enough

**Comment by Sophie-GelinasGagne** [comment]
@danbjoseph The logo still doesn't appear correctly, and looking at the Inspect view, the link has not changed. I'm wondering if there was another location where I should update the link, or if it is a delay in the changes?

**Comment by danbjoseph** [comment]
what's the URL for the page you're looking at?

**Comment by Sophie-GelinasGagne** [comment]
https://www.missingmaps.org/leaderboards/#/missingmaps

**Comment by danbjoseph** [comment]
the build process on the leaderboards failed with this error:
```
Dpl does not have permission to access github.com/MissingMaps/leaderboards.git using 
the provided GitHub token. Please make sure the token have the repo or public_repo scope.
```
i've tried updating the token with 3572c7699808b8fbd642fa2aa68664ba9e60837c

**Pull request merged**
