### PR TITLE
Point to new production endpoint

### PR DESCRIPTION
**Pull request by mojodna**
Numbers will differ, behavior will differ (only 500 users will be loaded at a time).

Supersedes #24

### CODE REVIEW

**Comment by dalekunce** [comment]
Need to add 0 when no buildings have been edited.

screen shot 2018-03-21 at 5 18 28 pm

**Comment by dalekunce** [comment]
Clean up the list of hashtags. Sometimes hashtags don't have spaces and show up funny. For example:

screen shot 2018-03-21 at 5 27 46 pm

**Comment by dalekunce** [comment]
Given the backfill these numbers should match the numbers on the massingmaps homepage.

screen shot 2018-03-21 at 5 32 29 pm

screen shot 2018-03-21 at 5 34 36 pm

**Comment by mojodna** [comment]
`0` is false-y in Java and it was falling back to `""`.

The hashtag selector was still pointed at the live API (osm-stats-api.azurewebsites.net), which includes funky hashtag names (no longer present).

Discrepancies between the home page and the #missingmaps card were resolved in https://github.com/MissingMaps/missingmaps.github.io/commit/8050b87506b66598782f82e3379bd0cc596538af (we no longer need to account for uncounted edits).

**Comment by mojodna** [comment]
@dalekunce have another look when you get a chance.

**Pull request merged**
